### ISSUE TITLE
stock deducted on order shipment

### ISSUE THREAD

**Issue by mshifo** [AmpersandHQ/magento2-disable-stock-reservation#20]
Magento ver. 2.3.4

stock deductions triggered on order placement and on order shipment !

also where is sales_order_save_after event ? i can't find it

**Comment by convenient** [comment]
Hello

https://travis-ci.org/github/AmpersandHQ/magento2-disable-stock-reservation/jobs/685783410

This test run is on 2.3.5-1

https://github.com/AmpersandHQ/magento2-disable-stock-reservation/blob/34421892917016beceb4ce869a77084c84f9b223/dev/tests/acceptance/CheckoutCest.php#L73-L90

This test covers
- Create simple product with 100 qty
- Add 3 of product to basket and check out
- See that we have 97 stock remaining (3 deducted)
- Ship 
- See that we have 97 stock remaining (3 deducted)

Are there other customisations that may be affecting you?

I see the README.md needs updated, the usage of that observer was replaced with a plugin in https://github.com/AmpersandHQ/magento2-disable-stock-reservation/pull/10

**Comment by mshifo** [comment]
thanks for your support!
No, I think there is not, the only customization i did is that i just changed the default order status of shipment to be "out for deliverery" instead of "complete".

I added the following to events.xml and stock deductions didn't triggered on shipment 
` <event name="sales_order_save_after">
<observer name="inventory_sales_source_deduction_processor" instance="Ampersand\DisableStockReservation\Plugin\SourceDeductionProcessor"/>
    </event>`

is that going to affect anything ? because it fixed the issue

**Comment by convenient** [comment]
@mshifo 

https://github.com/magento/inventory/blob/83fc7de7a53ae60ebc3115d62cd4119c725204f2/InventoryShipping/etc/events.xml#L11-L8

The only vanilla observer that I can see called `inventory_sales_source_deduction_processor` is the one we have disabled here

https://github.com/AmpersandHQ/magento2-disable-stock-reservation/blob/34421892917016beceb4ce869a77084c84f9b223/src/etc/events.xml#L6-L3

So what you are doing is adding another observer with that name on a different event, but `Ampersand\DisableStockReservation\Plugin\SourceDeductionProcessor` is not an observer so I don't think it will be picking anything up. Check your logs to see if its complaining?

The tests use the magento API so that they don't need a headless browser to run. It shouldn't make much of a difference as this is low level and hooks onto the order place and similar hooks.

**Comment by mshifo** [comment]
Yes I understand.
I removed the observer i added and it works now, may be there was something wrong in my configurations.
thank u very much, really appreciated

**Comment by convenient** [comment]
@mshifo good to hear it. Potentially some cache, or di compilation was holding onto old values.
